# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-13 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('celular', models.CharField(max_length=11)),
                ('cnh', models.CharField(max_length=11)),
                ('pontuacao', models.FloatField()),
                ('senha', models.CharField(max_length=8)),
            ],
        ),
    ]
