# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-12 16:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=10)),
                ('login', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_espera', 'Em Espera'), ('cancelada', 'Cancelada'), ('iniciada', 'Iniciada'), ('finalizada', 'Finalizada')], default='em_espera', max_length=20)),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('valor', models.FloatField(default=0.0)),
                ('horarioInicial', models.DateField(blank=True, null=True)),
                ('horarioFinal', models.DateField(blank=True, null=True)),
                ('pontuacao', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cpf', models.CharField(default='', max_length=11)),
                ('celular', models.CharField(default='', max_length=11)),
                ('cnh', models.CharField(default='', max_length=11)),
                ('pontuacao', models.FloatField(default=-1)),
                ('statusMotorista', models.BooleanField(default=True)),
                ('lastKnownLocation', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField(blank=True, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Motorista')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('licenciado', 'Licenciado'), ('n_licenciado', 'Não Licenciado')], default='n_licenciado', max_length=20)),
                ('cooperativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cooperativa')),
            ],
        ),
        migrations.AddField(
            model_name='uso',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Veiculo'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='motorista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Motorista'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='passageiro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Passageiro'),
        ),
    ]
