# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-13 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cooperativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('licenciado', 'Licenciado'), ('n_licenciado', 'Não Licenciado')], default='n_licenciado', max_length=20)),
            ],
        ),
    ]
