# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-10 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em_espera', 'Em Espera'), ('cancelada', 'Cancelada'), ('iniciada', 'Iniciada'), ('finalizada', 'Finalizada')], default='em_espera', max_length=20)),
                ('origem', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('valor', models.FloatField(default=0.0)),
                ('horarioInicial', models.DateField(blank=True, null=True)),
                ('horarioFianl', models.DateField(blank=True, null=True)),
                ('pontuacao', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=200)),
                ('senha', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Uso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='motorista',
            name='cooperativa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Cooperativa'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='statusMotorista',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cooperativa',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Cooperativa'),
        ),
        migrations.AddField(
            model_name='uso',
            name='motorista',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Motorista'),
        ),
        migrations.AddField(
            model_name='uso',
            name='veiculo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Veiculo'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='motorista',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Motorista'),
        ),
        migrations.AddField(
            model_name='corrida',
            name='passageiro',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Passageiro'),
        ),
    ]
