# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-10 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170110_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorista',
            name='cooperativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cooperativa'),
        ),
    ]
