# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-10 15:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170110_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corrida',
            old_name='horarioFianl',
            new_name='horarioFinal',
        ),
    ]
