# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170110_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrida',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Motorista'),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='passageiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Passageiro'),
        ),
        migrations.AlterField(
            model_name='uso',
            name='motorista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Motorista'),
        ),
        migrations.AlterField(
            model_name='uso',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Veiculo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='cooperativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Cooperativa'),
        ),
    ]
